"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const utils_1 = require("./utils");
// const _gcd = gcd(562668,896400);
// const res = exGcd(562668,896400);
// console.log(`GCD is ${_gcd}`);
// console.log(res);
// console.log(`verify ${res.calcGcd()}`);
const primitves = (0, utils_1.findPrimitive)(10000000);
console.log(primitves);
